kind: Deployment
apiVersion: apps/v1
metadata:
  name: dogs-deployment
  namespace: k8sprimitives1
  labels:
    app: nginx
    release: dogs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      release: dogs
  template:
    metadata:
      labels:
        app: nginx
        release: dogs
    spec:
      containers:
        - name: nginx
          image: 'index.docker.io/belitre/nginx:0.1'
          imagePullPolicy: IfNotPresent
          env:
            - name: CONF_TEMPLATE
              value: '/var/conf/default.conf'
            - name: HTML_PATH
              value: '/var/git/k8sprimitives1/resources/dogs'
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          volumeMounts:
            - name: git-repo
              readOnly: true
              mountPath: /var/git
            - name: nginx-conf
              readOnly: true
              mountPath: /var/conf
          resources:
            limits:
              cpu: "0.1"
              memory: "50M"
            requests:
              cpu: "0.1"
              memory: "50M"
        - name: git-sync
          image: 'index.docker.io/belitre/git-sync:0.1'
          imagePullPolicy: IfNotPresent
          env:
            - name: GIT_SYNC_REPO
              value: 'https://github.com/ouzi-dev/k8sprimitives1'
            - name: GIT_SYNC_BRANCH
              value: master
            - name: GIT_SYNC_WAIT
              value: '300'
            - name: GIT_SYNC_DEST
              value: k8sprimitives1
          volumeMounts:
            - name: git-repo
              mountPath: /git
          resources:
            limits:
              cpu: "0.1"
              memory: "50M"
            requests:
              cpu: "0.1"
              memory: "50M"
      volumes:
        - name: git-repo
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-template